# Generated by Django 3.1.2 on 2020-10-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Main', '0002_auto_20201027_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='spend_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='Main.spendcategory'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='Accounts.profile'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='Accounts.profile'),
        ),
    ]
