# Generated by Django 3.1.2 on 2020-10-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Main', '0006_auto_20201027_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='balance_due_currency',
        ),
        migrations.AddField(
            model_name='outgoingpayment',
            name='spend_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='Main.spendcategory'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='income_categories', to='Accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='Accounts.profile'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='spend_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='Main.spendcategory'),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Main.bankaccount'),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Main.creditcard'),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Main.merchant'),
        ),
    ]
