# Generated by Django 3.1.2 on 2020-10-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Main', '0008_auto_20201028_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingpayment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_payments', to='Accounts.profile'),
        ),
    ]
