# Generated by Django 3.1.2 on 2020-10-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20201028_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingpayment',
            name='income_category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='Main.incomecategory'),
            preserve_default=False,
        ),
    ]
