# Generated by Django 3.1.2 on 2020-10-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Main', '0014_auto_20201028_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendcategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_categories', to='Accounts.profile'),
        ),
    ]
