# Generated by Django 3.1.2 on 2020-10-29 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20201029_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 23, 47, 27, 374314)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 23, 47, 27, 374314)),
        ),
    ]
