# Generated by Django 3.1.2 on 2020-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20201102_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
