# Generated by Django 3.1.2 on 2020-11-02 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_auto_20201102_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 21, 34, 3, 44243)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 21, 34, 3, 44243)),
        ),
    ]
