# Generated by Django 3.1.2 on 2020-11-03 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20201102_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 14, 42, 10, 895374)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 14, 42, 10, 895374)),
        ),
    ]
