# Generated by Django 3.1.2 on 2020-11-03 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20201103_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='spend_category',
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 52, 43, 202198)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 52, 43, 202198)),
        ),
    ]
