# Generated by Django 3.1.2 on 2020-11-03 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_auto_20201103_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='category',
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 16, 46, 46, 479920)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 16, 46, 46, 479920)),
        ),
    ]
