# Generated by Django 3.1.2 on 2020-11-03 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_auto_20201103_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecategory',
            old_name='profiles',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 16, 58, 21, 784340)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 16, 58, 21, 784340)),
        ),
    ]
