# Generated by Django 3.1.2 on 2020-11-03 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_auto_20201103_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 17, 43, 48, 69723)),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 17, 43, 48, 69723)),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 17, 43, 48, 66722)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 17, 43, 48, 66722)),
        ),
    ]
