# Generated by Django 3.1.2 on 2020-11-03 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20201103_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransfer',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 22, 48, 43, 960257)),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 22, 48, 43, 960257)),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 22, 48, 43, 957526)),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 22, 48, 43, 957526)),
        ),
    ]
